### ISSUE TITLE
I have too many absolute_bounty_residual points :(

### ISSUE THREAD

**Issue by Silox** [ZeusWPI/gamification#92]
```
F, [2016-04-25T21:16:24.849106 #27990] FATAL -- : 
ActiveRecord::StatementInvalid (Mysql2::Error: Out of range value for column 'absolute_bounty_residual' at row 1: UPDATE `coders` SET `absolute_bounty_residual` = 2330958253, `reward_residual` = 17075, `updated_at` = '2016-04-25 19:16:23' WHERE `coders`.`id` = 1):
  app/models/coder.rb:57:in `reward_commit!'
  app/models/commit.rb:31:in `reward!'
  app/models/commit.rb:47:in `block in register_rugged'
  app/models/commit.rb:43:in `register_rugged'
  app/models/commit.rb:36:in `register_from_sha'
  app/controllers/webhooks_controller.rb:31:in `block in push'
  app/controllers/webhooks_controller.rb:30:in `each'
  app/controllers/webhooks_controller.rb:30:in `push'
  app/controllers/webhooks_controller.rb:10:in `receive'
```

**Comment by NoctuaNivalis** [comment]
lol mysql

**Comment by Procrat** [comment]
https://moeffju.net/blog/using-bigint-columns-in-rails-migrations
